
import { Opportunity, UserProfile, SuccessStory, Partner, LearningResource, Language } from './types';

// Translation Dictionary
export const TRANSLATIONS = {
  en: {
    welcome: "Guiding Youths Into Opportunity",
    platform: "Platform",
    feed: "Opportunities Feed",
    mentorship: "Mentorship Hub",
    partners: "Partners & Experts",
    learning: "Learning Center",
    personal: "Personal",
    profile: "My Profile",
    contribute: "Contribute",
    settings: "Settings",
    admin: "Admin Dashboard",
    mentorDash: "Mentor Dashboard",
    topExperts: "Top Experts This Week",
    signOut: "Sign Out",
    searchPlaceholder: "Search opportunities...",
    aiOn: "AI Active",
    aiOff: "Enable AI",
    filters: "Filters",
    apply: "Apply Now",
    deadline: "Deadline",
    posted: "Posted",
    online: "Online",
    myRegion: "My Region",
    successStories: "Success Stories",
    viewDetails: "View Details",
    showLess: "Show Less",
    eligibility: "Eligibility",
    benefits: "Benefits",
    requirements: "Requirements",
    verifiedMentors: "Verified Mentors",
    viewAll: "View All",
    noOpportunities: "No opportunities found.",
    tryAdjusting: "Try adjusting your filters or search."
  },
  fr: {
    welcome: "Guider les jeunes vers l'opportunité",
    platform: "Plateforme",
    feed: "Fil d'opportunités",
    mentorship: "Mentorat",
    partners: "Partenaires & Experts",
    learning: "Centre d'apprentissage",
    personal: "Personnel",
    profile: "Mon Profil",
    contribute: "Contribuer",
    settings: "Paramètres",
    admin: "Tableau de bord Admin",
    mentorDash: "Tableau de bord Mentor",
    topExperts: "Experts de la semaine",
    signOut: "Déconnexion",
    searchPlaceholder: "Rechercher des opportunités...",
    aiOn: "IA Active",
    aiOff: "Activer IA",
    filters: "Filtres",
    apply: "Postuler",
    deadline: "Date limite",
    posted: "Publié",
    online: "En ligne",
    myRegion: "Ma Région",
    successStories: "Histoires de succès",
    viewDetails: "Voir Détails",
    showLess: "Voir Moins",
    eligibility: "Éligibilité",
    benefits: "Avantages",
    requirements: "Prérequis",
    verifiedMentors: "Mentors Vérifiés",
    viewAll: "Voir Tout",
    noOpportunities: "Aucune opportunité trouvée.",
    tryAdjusting: "Essayez d'ajuster vos filtres."
  },
  pidgin: {
    welcome: "We Di Show Wuna Road for Opportunity",
    platform: "Di Platform",
    feed: "Opportunities Dem",
    mentorship: "Mentorship Corner",
    partners: "People Weh Di Help",
    learning: "Place for Learn",
    personal: "Ma Own Thing",
    profile: "Ma Profile",
    contribute: "Add Your Own",
    settings: "Settings",
    admin: "Oga Dashboard",
    mentorDash: "Mentor Dashboard",
    topExperts: "Big Man Dem This Week",
    signOut: "Comot",
    searchPlaceholder: "Find work, school or money...",
    aiOn: "AI Dey On",
    aiOff: "Put AI On",
    filters: "Select Weytin U Want",
    apply: "Apply Here",
    deadline: "Time Di Finish",
    posted: "Dem Post Am",
    online: "For Internet",
    myRegion: "Ma Side",
    successStories: "People Weh Don Hammer",
    viewDetails: "See Full Tori",
    showLess: "Close Am Small",
    eligibility: "Who Fit Apply",
    benefits: "Weytin U Go Gain",
    requirements: "Weytin Dem Want",
    verifiedMentors: "Mentors Weh We Sabi",
    viewAll: "See All",
    noOpportunities: "Nothing dey for here.",
    tryAdjusting: "Try change wetin you di find."
  },
  de: {
    welcome: "Jugendliche zu Chancen führen",
    platform: "Plattform",
    feed: "Möglichkeiten",
    mentorship: "Mentoring-Hub",
    partners: "Partner & Experten",
    learning: "Lernzentrum",
    personal: "Persönlich",
    profile: "Mein Profil",
    contribute: "Beitragen",
    settings: "Einstellungen",
    admin: "Admin-Dashboard",
    mentorDash: "Mentor-Dashboard",
    topExperts: "Top-Experten diese Woche",
    signOut: "Abmelden",
    searchPlaceholder: "Möglichkeiten suchen...",
    aiOn: "KI Aktiv",
    aiOff: "KI Aktivieren",
    filters: "Filter",
    apply: "Jetzt bewerben",
    deadline: "Frist",
    posted: "Gepostet",
    online: "Online",
    myRegion: "Meine Region",
    successStories: "Erfolgsgeschichten",
    viewDetails: "Details anzeigen",
    showLess: "Weniger anzeigen",
    eligibility: "Berechtigung",
    benefits: "Vorteile",
    requirements: "Anforderungen",
    verifiedMentors: "Verifizierte Mentoren",
    viewAll: "Alle anzeigen",
    noOpportunities: "Keine Möglichkeiten gefunden.",
    tryAdjusting: "Versuchen Sie, Ihre Filter anzupassen."
  },
  zh: {
    welcome: "引导青年走向机遇",
    platform: "平台",
    feed: "机会动态",
    mentorship: "导师中心",
    partners: "合作伙伴",
    learning: "学习中心",
    personal: "个人中心",
    profile: "我的资料",
    contribute: "贡献",
    settings: "设置",
    admin: "管理后台",
    mentorDash: "导师后台",
    topExperts: "本周专家",
    signOut: "退出登录",
    searchPlaceholder: "搜索机会...",
    aiOn: "AI 已开启",
    aiOff: "开启 AI",
    filters: "筛选",
    apply: "立即申请",
    deadline: "截止日期",
    posted: "发布于",
    online: "在线",
    myRegion: "我的地区",
    successStories: "成功案例",
    viewDetails: "查看详情",
    showLess: "收起详情",
    eligibility: "资格要求",
    benefits: "福利待遇",
    requirements: "申请要求",
    verifiedMentors: "认证导师",
    viewAll: "查看全部",
    noOpportunities: "未找到相关机会。",
    tryAdjusting: "尝试调整筛选条件。"
  },
  es: {
    welcome: "Guiando a los jóvenes hacia oportunidades",
    platform: "Plataforma",
    feed: "Oportunidades",
    mentorship: "Centro de Mentoría",
    partners: "Socios y Expertos",
    learning: "Centro de Aprendizaje",
    personal: "Personal",
    profile: "Mi Perfil",
    contribute: "Contribuir",
    settings: "Ajustes",
    admin: "Panel de Admin",
    mentorDash: "Panel de Mentor",
    topExperts: "Expertos destacados",
    signOut: "Cerrar sesión",
    searchPlaceholder: "Buscar oportunidades...",
    aiOn: "IA Activa",
    aiOff: "Activar IA",
    filters: "Filtros",
    apply: "Aplicar ahora",
    deadline: "Fecha límite",
    posted: "Publicado",
    online: "En línea",
    myRegion: "Mi Región",
    successStories: "Historias de éxito",
    viewDetails: "Ver detalles",
    showLess: "Ver menos",
    eligibility: "Elegibilidad",
    benefits: "Beneficios",
    requirements: "Requisitos",
    verifiedMentors: "Mentores verificados",
    viewAll: "Ver todo",
    noOpportunities: "No se encontraron oportunidades.",
    tryAdjusting: "Intenta ajustar tus filtros."
  }
};

// Hardcoded Admin Credentials
export const ADMIN_CREDENTIALS = [
  { email: 'azilmuluh@gmail.com', pass: '119402008', name: 'Muluh Azinwi Success' },
  { email: 'nellybong20@gmail.com', pass: 'Nels-12', name: 'Chang Nelly Brown Bong' },
  { email: 'nyingchoadih@gmail.com', pass: 'Ngwanyingchogodwin2014#11', name: 'Nyingcho Bianca Adih' },
  { email: 'fodjonelson22@gmail.com', pass: 'nelcoteaches#0735', name: 'Fodjo Nelson' }
];

// Specific Mentor Credentials
export const MENTOR_CREDENTIALS = [
  { email: 'azinwindahi@gmail.com', pass: '119402008', name: 'Muluh Ndahi' }
];

// Pre-approved Mentor Emails
export const MENTOR_WHITELIST = [
  'mentor@launchpad.com',
  'expert@tech.cm',
  'dr.kamga@university.cm',
  'azinwindahi@gmail.com'
];

export const MOCK_USER: UserProfile = {
  id: 'u1',
  name: "Arrey Etta",
  username: "@arrey_tech",
  email: "arrey@example.com",
  role: 'User',
  education: "Undergraduate",
  academicBackground: "Software Engineering",
  graduationYear: "2025",
  interests: ["Technology", "Startups", "Community Development"],
  specificNeeds: ["Mentorship", "Funding"],
  targetCategories: ["Internship", "Hackathon"],
  city: "Buea",
  country: "Cameroon",
  age: 21,
  gender: "Male",
  bio: "UB Student. Silicon Mountain enthusiast. Building for Africa.",
  language: 'en',
  opportunitiesApplied: 8,
  opportunitiesSaved: 12,
  achievements: ["Profile Completed", "Hackathon Finalist"],
  settings: {
      notifications: true,
      push: true,
      reminders: true,
      news: false,
      privacyProfile: true
  }
};

export const MOCK_MENTORS: UserProfile[] = [
  {
    id: 'm1',
    name: "Dr. Chioma Okeke",
    username: "@dr_chioma",
    email: "chioma@example.com",
    role: 'Mentor',
    education: "PhD Computer Science",
    city: "Lagos",
    country: "Nigeria",
    age: 35,
    gender: "Female",
    interests: ["AI", "Research"],
    bio: "AI Researcher helping African students get into top global grad schools.",
    profession: "AI Researcher",
    currentRole: "Senior Lecturer, UNILAG",
    yearsExperience: 10,
    expertise: ["Artificial Intelligence", "Academic Research", "Grant Writing"],
    availability: "Weekly",
    services: ["Academic Guidance", "Project Mentorship", "Scholarship Guidance"],
    rating: 4.9,
    reviewCount: 45,
    linkedinLink: "#",
    achievements: ["Top Mentor 2023"]
  },
  {
    id: 'm2',
    name: "Sarah Tabe",
    username: "@sarah_pm",
    email: "sarah@example.com",
    role: 'Mentor',
    education: "MBA",
    city: "Douala",
    country: "Cameroon",
    age: 29,
    gender: "Female",
    interests: ["Business", "Fintech"],
    bio: "Fintech Product Manager at MTN. I help young pros navigate the corporate ladder.",
    profession: "Product Manager",
    currentRole: "Product Lead, MTN Cameroon",
    yearsExperience: 7,
    expertise: ["Product Management", "Fintech", "Career Strategy"],
    availability: "Monthly",
    services: ["CV Review", "Interview Prep", "Career Advice"],
    rating: 5.0,
    reviewCount: 28,
    linkedinLink: "#"
  },
  {
    id: 'm3',
    name: "Blaise Fomonyuy",
    username: "@blaise_dev",
    email: "blaise@example.com",
    role: 'Mentor',
    education: "B.Eng Software",
    city: "Buea",
    country: "Cameroon",
    age: 26,
    gender: "Male",
    interests: ["Software", "Startups"],
    bio: "Silicon Mountain Founder. Let's review your code and portfolio.",
    profession: "Software Engineer",
    currentRole: "CTO, Skylight Tech",
    yearsExperience: 5,
    expertise: ["Software Engineering", "React", "Startup Fundraising"],
    availability: "Weekly",
    services: ["Portfolio Review", "Project Mentorship"],
    rating: 4.8,
    reviewCount: 32,
    linkedinLink: "#"
  }
];

export const INITIAL_SUCCESS_STORIES: SuccessStory[] = [
  {
    id: 's1',
    authorName: 'Teboh Melvine',
    title: 'From Buea to Google!',
    content: 'Thanks to the LaunchPad mentorship program, I polished my CV and landed a remote role. The community support is real!',
    date: '2024-09-15',
    status: 'approved'
  }
];

export const MOCK_PARTNERS: Partner[] = [
  { id: 'p1', name: 'MTN Cameroon', logo: 'M', description: 'Leading telecommunications provider supporting local tech talent.', category: 'Corporate', website: '#' },
  { id: 'p2', name: 'ActivSpaces', logo: 'AS', description: 'The first tech hub in Cameroon, supporting startups in Buea and Douala.', category: 'Tech', website: '#' },
  { id: 'p3', name: 'Silicon Mountain', logo: 'SM', description: 'Community of techies and innovators in the Fako region.', category: 'Tech', website: '#' },
  { id: 'p4', name: 'Orange Digital Center', logo: 'O', description: 'Free digital training and support for youth.', category: 'Education', website: '#' },
  { id: 'p5', name: 'University of Buea', logo: 'UB', description: 'Partnering for student research grants.', category: 'Education', website: '#' },
];

export const MOCK_RESOURCES: LearningResource[] = [
  { id: 'r1', title: 'Winning Chevening Essays from Cameroon', type: 'Guide', author: 'LaunchPad Team', category: 'Scholarship', link: 'https://example.com/guide.pdf' },
  { id: 'r2', title: 'Intro to Tech in Cameroon', type: 'Video', author: 'Silicon Mountain', duration: '1h 30m', category: 'Tech', link: 'https://youtube.com' },
  { id: 'r3', title: 'CV Template for Cameroonian Graduates', type: 'Guide', author: 'Sarah Tabe', category: 'Career', link: 'https://example.com/cv-template.docx' },
  { id: 'r4', title: 'Startups in Francophone Africa', type: 'Video', author: 'Digital Africa', duration: '45m', category: 'Business', link: 'https://youtube.com' },
  { id: 'r5', title: 'Research Grant Proposal Writing', type: 'Course', author: 'Coursera', duration: '12h', category: 'Research', link: 'https://coursera.org' },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: '1',
    title: 'Silicon Mountain Code Fest 2024',
    organization: 'Silicon Mountain Community',
    logo: 'https://ui-avatars.com/api/?name=SM&background=0D8ABC&color=fff&size=128',
    category: 'Hackathon',
    regionScope: 'Specific City',
    location: 'Buea',
    isOnline: false,
    deadline: '2024-11-20',
    description: 'The biggest onsite coding competition in Buea. Gather your team and build solutions for local problems.',
    tags: ['Coding', 'Java', 'Community'],
    postedAt: '2h ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Students and Devs in Fako.',
    requirements: ['Laptop', 'Team of 3'],
    benefits: '1M XAF Prize Pool, Job Offers',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate', 'Self-Taught']
  },
  {
    id: '2',
    title: 'Orange Cameroon Pulse Internship',
    organization: 'Orange Cameroon',
    logo: 'https://ui-avatars.com/api/?name=Orange&background=FF7900&color=fff&size=128',
    category: 'Internship',
    regionScope: 'Cameroon',
    location: 'Douala',
    isOnline: false,
    deadline: '2024-11-05',
    description: 'Join the digital team at Orange. Looking for frontend developers and UI/UX designers.',
    tags: ['Corporate', 'Tech', 'Telecom'],
    postedAt: '5h ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Final year students (Licence/Master).',
    requirements: ['CV', 'Portfolio', 'School Letter'],
    benefits: 'Monthly Allowance (80k XAF), Experience',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate', 'Graduate']
  },
  {
    id: '3',
    title: 'Presidential Excellence Grant',
    organization: 'MinESUP',
    logo: 'https://ui-avatars.com/api/?name=Min&background=007A33&color=fff&size=128',
    category: 'Grant',
    regionScope: 'Cameroon',
    location: 'Yaoundé',
    isOnline: false,
    deadline: '2024-12-31',
    description: 'Academic excellence grant for top performing university students in state universities.',
    tags: ['Government', 'Education'],
    postedAt: '1d ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'GPA > 3.5/4.0.',
    requirements: ['Transcripts', 'ID'],
    benefits: '50,000 XAF Grant',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate', 'Graduate']
  },
  {
    id: '4',
    title: 'Mastercard Foundation Scholars Program',
    organization: 'Mastercard Foundation',
    logo: 'https://ui-avatars.com/api/?name=MF&background=CF2C22&color=fff&size=128',
    category: 'Scholarship',
    regionScope: 'Africa',
    location: 'Cape Town',
    isOnline: false,
    deadline: '2025-01-15',
    description: 'Full scholarship for African students to study at UCT South Africa.',
    tags: ['Study Abroad', 'Full Ride'],
    postedAt: '3d ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Academically talented African youth.',
    requirements: ['Essays', 'References', 'Transcripts'],
    benefits: 'Full Tuition, Accommodation, Stipend, Flight',
    applicationLink: '#',
    targetEducationLevels: ['Graduate', 'Undergraduate']
  },
  {
    id: '5',
    title: 'Bamenda Innovation Week Volunteer',
    organization: 'Bamenda Tech Hub',
    logo: 'https://ui-avatars.com/api/?name=BT&background=4B5563&color=fff&size=128',
    category: 'Volunteering',
    regionScope: 'Specific City',
    location: 'Bamenda',
    isOnline: false,
    deadline: '2024-10-30',
    description: 'Help organize the biggest tech event in the North West region.',
    tags: ['Event', 'Community'],
    postedAt: '6h ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Residents of Bamenda.',
    requirements: ['Availability'],
    benefits: 'Certificate, T-Shirt, Networking',
    applicationLink: '#',
    targetEducationLevels: ['High School', 'Undergraduate']
  },
  {
    id: '6',
    title: 'Remote Technical Writer',
    organization: 'AfriTech Blog',
    logo: 'https://ui-avatars.com/api/?name=AT&background=8B5CF6&color=fff&size=128',
    category: 'Job',
    regionScope: 'Africa',
    location: 'Remote',
    isOnline: true,
    deadline: 'Rolling',
    description: 'Write tutorials about using mobile money APIs in Africa.',
    tags: ['Writing', 'Fintech'],
    postedAt: '1w ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Strong English writing skills.',
    requirements: ['Writing Samples'],
    benefits: '$50 per article',
    applicationLink: '#',
    targetEducationLevels: ['All']
  },
  {
    id: '7',
    title: 'Canal 2 International Journalism Intern',
    organization: 'Canal 2',
    logo: 'https://ui-avatars.com/api/?name=C2&background=EF4444&color=fff&size=128',
    category: 'Internship',
    regionScope: 'Cameroon',
    location: 'Douala',
    isOnline: false,
    deadline: '2024-11-15',
    description: 'Internship for journalism students interested in TV production.',
    tags: ['Media', 'Journalism'],
    postedAt: '2d ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Journalism students.',
    requirements: ['CV', 'Demo Reel (Optional)'],
    benefits: 'Transport Allowance',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate']
  },
  {
    id: '8',
    title: 'AgriTech Seed Fund',
    organization: 'Cameroon Angel Investors',
    logo: 'https://ui-avatars.com/api/?name=CA&background=10B981&color=fff&size=128',
    category: 'Grant',
    regionScope: 'Cameroon',
    location: 'Remote',
    isOnline: true,
    deadline: '2025-02-01',
    description: 'Seed funding for startups improving agriculture in Cameroon.',
    tags: ['Startup', 'Agriculture'],
    postedAt: '4d ago',
    status: 'approved',
    authorRole: 'Mentor',
    cost: 'Free',
    eligibility: 'Registered startup.',
    requirements: ['Pitch Deck', 'Prototype'],
    benefits: '2M XAF Investment',
    applicationLink: '#',
    targetEducationLevels: ['All']
  },
  {
    id: '9',
    title: 'UB Buea Science Fair',
    organization: 'University of Buea',
    logo: 'https://ui-avatars.com/api/?name=UB&background=3B82F6&color=fff&size=128',
    category: 'Competition',
    regionScope: 'Specific City',
    location: 'Buea',
    isOnline: false,
    deadline: '2024-11-01',
    description: 'Science exhibition for STEM students.',
    tags: ['Science', 'STEM'],
    postedAt: '12h ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'UB Students.',
    requirements: ['Project Abstract'],
    benefits: 'Awards, Recognition',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate']
  },
  {
    id: '10',
    title: 'Douala Digital Marketing Masterclass',
    organization: 'DigiCam',
    logo: 'https://ui-avatars.com/api/?name=DC&background=EC4899&color=fff&size=128',
    category: 'Event',
    regionScope: 'Specific City',
    location: 'Douala',
    isOnline: false,
    deadline: '2024-10-25',
    description: '2-day workshop on SEO and Social Media Marketing.',
    tags: ['Marketing', 'Business'],
    postedAt: '1d ago',
    status: 'approved',
    authorRole: 'Mentor',
    cost: 'Paid',
    costAmount: '15,000 XAF',
    eligibility: 'Open to all.',
    requirements: ['Laptop'],
    benefits: 'Certificate',
    applicationLink: '#',
    targetEducationLevels: ['All']
  },
  {
    id: '11',
    title: 'Tony Elumelu Entrepreneurship Programme',
    organization: 'TEF',
    logo: 'https://ui-avatars.com/api/?name=TE&background=DC2626&color=fff&size=128',
    category: 'Grant',
    regionScope: 'Africa',
    location: 'Remote',
    isOnline: true,
    deadline: '2025-01-01',
    description: '$5000 seed capital for African entrepreneurs with a business idea.',
    tags: ['Business', 'Funding', 'Startup'],
    postedAt: '2d ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'African residents with business ideas.',
    requirements: ['Business Plan', 'ID'],
    benefits: '$5000 Grant, Training, Mentorship',
    applicationLink: '#',
    targetEducationLevels: ['All']
  },
  {
    id: '12',
    title: 'Study in Canada Seminar',
    organization: 'Open Doors',
    logo: 'https://ui-avatars.com/api/?name=OD&background=F59E0B&color=fff&size=128',
    category: 'Event',
    regionScope: 'Specific City',
    location: 'Yaoundé',
    isOnline: false,
    deadline: '2024-10-28',
    description: 'Information session on applying to Canadian universities.',
    tags: ['Study Abroad', 'Education'],
    postedAt: '5h ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Students and Parents.',
    requirements: ['Registration'],
    benefits: 'Free Counselling',
    applicationLink: '#',
    targetEducationLevels: ['High School', 'Undergraduate']
  },
  {
    id: '13',
    title: 'Junior Graphic Designer',
    organization: 'KiroGames',
    logo: 'https://ui-avatars.com/api/?name=KG&background=8B5CF6&color=fff&size=128',
    category: 'Job',
    regionScope: 'Cameroon',
    location: 'Yaoundé',
    isOnline: false,
    deadline: '2024-11-20',
    description: 'Design assets for a local gaming studio.',
    tags: ['Design', 'Gaming'],
    postedAt: '3d ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Portfolio required.',
    requirements: ['Portfolio', 'Photoshop'],
    benefits: 'Salary',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate', 'Self-Taught']
  },
  {
    id: '14',
    title: 'Google Developer Student Clubs Lead',
    organization: 'Google',
    logo: 'https://ui-avatars.com/api/?name=GD&background=4285F4&color=fff&size=128',
    category: 'Volunteering',
    regionScope: 'Global',
    location: 'Campus Based',
    isOnline: false,
    deadline: '2024-05-30',
    description: 'Lead a tech community on your campus (UB, UY1, etc.).',
    tags: ['Leadership', 'Tech'],
    postedAt: '1w ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'University students.',
    requirements: ['Video Application'],
    benefits: 'Network, Swag, Travel',
    applicationLink: '#',
    targetEducationLevels: ['Undergraduate']
  },
  {
    id: '15',
    title: 'Medical Elective in Limbe',
    organization: 'Limbe Regional Hospital',
    logo: 'https://ui-avatars.com/api/?name=LR&background=EF4444&color=fff&size=128',
    category: 'Internship',
    regionScope: 'Cameroon',
    location: 'Limbe',
    isOnline: false,
    deadline: '2024-12-01',
    description: 'Practical experience for med students.',
    tags: ['Health', 'Medicine'],
    postedAt: '4d ago',
    status: 'approved',
    authorRole: 'Admin',
    cost: 'Free',
    eligibility: 'Med students (4th year+).',
    requirements: ['School Letter'],
    benefits: 'Clinical Experience',
    applicationLink: '#',
    targetEducationLevels: ['Graduate']
  }
];

export const CATEGORIES = [
  'All',
  'Scholarship',
  'Internship',
  'Hackathon',
  'Grant',
  'Volunteering',
  'Fellowship',
  'Competition',
  'Job',
  'Event'
];
